server:
  port: 8000

spring:
  application:
    name: SION

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout : 6000ms # 연결 타임아웃
      lettuce:
        pool:
          max-active: 10  # 최대 활성 연결 수
          max-idle: 5  # 최대 유휴 연결 수
          min-idle: 1  # 최소 유휴 연결 수
          max-wait: 2000ms  # 최대 대기 시간

#logging:
#  level:
#    root: DEBUG
#    com.nexus.sion: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /v3/api-docs

cloud:
  aws:
    active: true
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET}