server:
  port: 8000

spring:
  application:
    name: SION

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sion}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 2000ms

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: >
    com.nexus.sion.feature.squad.query.mapper
    com.nexus.sion.feature.auth.query.mapper
    com.nexus.sion.feature.evaluation.query.mapper
    com.nexus.sion.feature.member.query.mapper
    com.nexus.sion.feature.project.query.mapper
    com.nexus.sion.feature.statistics.query.mapper
    com.nexus.sion.feature.techstack.query.mapper
  configuration:
    map-underscore-to-camel-case: true
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: ${JWT_SECRET:this-is-a-secret}
  expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /v3/api-docs

cloud:
  aws:
    active: true
    credentials:
      access-key: ${AWS_ACCESS_KEY:dummy-access-key}
      secret-key: ${AWS_SECRET_KEY:dummy-secret-key}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET:dummy-bucket-name}

logging:
  level:
    root: INFO
    com.nexus.sion: INFO
    org.mybatis: DEBUG
    jdbc.sqlonly: DEBUG
    com.nexus.sion.feature.squad.query.mapper: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus"]

ai:
  fp-infer: http://localhost:8100/fp-infer
  embed-function: http://localhost:8100/fp-embed
  fp-freelencer-infer: http://localhost:8100/fp-freelancer-infer

