
CREATE TABLE user_certificate_history (
                                          user_certificate_history_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          updated_by VARCHAR(30),
                                          certificate_name VARCHAR(100) NOT NULL,
                                          employee_identification_number VARCHAR(30) NOT NULL,
                                          PRIMARY KEY (user_certificate_history_id)
);

CREATE TABLE job (
                     name VARCHAR(30) NOT NULL,
                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     PRIMARY KEY (name)
);

CREATE TABLE project_evaluation (
                                    project_evaluation_id BIGINT NOT NULL,
                                    project_code VARCHAR(30) NOT NULL,
                                    developer_id BIGINT NOT NULL,
                                    estimator_id BIGINT NOT NULL,
                                    tech_fit INT NOT NULL,
                                    communication INT NOT NULL,
                                    problem_solving INT NOT NULL,
                                    cooperation_attitude INT NOT NULL,
                                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    PRIMARY KEY (project_evaluation_id)
);

CREATE TABLE project_fp_summary (
                                    project_fp_summary_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    total_fp INT NOT NULL,
                                    avg_effort_per_fp INT NOT NULL,
                                    total_effort DECIMAL(6, 2),
                                    estimated_duration DECIMAL(5, 2),
                                    estimated_cost DECIMAL(12, 2),
                                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    project_code VARCHAR(30) NOT NULL,
                                    PRIMARY KEY (project_fp_summary_id)
);

CREATE TABLE project_function_estimate (
                                           project_function_estimate_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                           function_name VARCHAR(100) NOT NULL,
                                           function_type VARCHAR(10) NOT NULL,
                                           complexity VARCHAR(10) NOT NULL,
                                           function_score INT NOT NULL,
                                           description TEXT,
                                           related_tables_count INT NOT NULL,
                                           related_fields_count INT,
                                           created_at TIMESTAMP,
                                           project_fp_summary_id BIGINT NOT NULL,
                                           PRIMARY KEY (project_function_estimate_id)
);

CREATE TABLE initial_score (
                               id BIGINT NOT NULL,
                               years INT NOT NULL,
                               score INT NOT NULL,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               PRIMARY KEY (id)
);

CREATE TABLE squad_comment (
                               comment_id BIGINT NOT NULL,
                               squad_code VARCHAR(30) NOT NULL,
                               employee_identification_number VARCHAR(30) NOT NULL,
                               content TEXT NOT NULL,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               PRIMARY KEY (comment_id)
);

CREATE TABLE project (
                         project_code VARCHAR(30) NOT NULL,
                         description TEXT NOT NULL,
                         title VARCHAR(30) NOT NULL,
                         budget BIGINT NOT NULL,
                         start_date DATE NOT NULL,
                         expected_end_date DATE NOT NULL,
                         actual_end_date DATE NOT NULL,
                         status VARCHAR(30) NOT NULL,
                         number_of_members INT,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         deleted_at TIMESTAMP,
                         client_code VARCHAR(30) NOT NULL,
                         request_specification_url VARCHAR(255) NOT NULL,
                         name VARCHAR(30) NOT NULL,
                         PRIMARY KEY (project_code)
);

CREATE TABLE grade (
                       grade_code VARCHAR(10) NOT NULL,
                       min_score INT NOT NULL,
                       max_score INT,
                       productivity DECIMAL(10, 4) NOT NULL,
                       monthly_unit_price INT NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       PRIMARY KEY (grade_code)
);

CREATE TABLE project_and_job (
                                 project_and_job_id BIGINT NOT NULL,
                                 required_number INT NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 project_code VARCHAR(30) NOT NULL,
                                 job_name VARCHAR(30) NOT NULL,
                                 PRIMARY KEY (project_and_job_id)
);

CREATE TABLE client_company (
                                client_code VARCHAR(30) NOT NULL,
                                company_name VARCHAR(255),
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                contact_person VARCHAR(10),
                                email VARCHAR(30),
                                contact_number VARCHAR(21),
                                domain_name VARCHAR(30) NOT NULL,
                                PRIMARY KEY (client_code)
);

CREATE TABLE developer_tech_stack_history (
                                              developer_tech_stack_history_id BIGINT NOT NULL,
                                              developer_tech_stack_id BIGINT NOT NULL,
                                              added_score INT NOT NULL,
                                              cumulative_score INT NOT NULL,
                                              related_table VARCHAR(30) NOT NULL,
                                              related_id BIGINT NOT NULL,
                                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                              updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                              PRIMARY KEY (developer_tech_stack_history_id)
);

CREATE TABLE developer_tech_stack (
                                      developer_tech_stack_id BIGINT NOT NULL,
                                      tech_stack_total_scores INT NOT NULL,
                                      employee_identification_number VARCHAR(30) NOT NULL,
                                      tech_stack_name VARCHAR(30) NOT NULL,
                                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      PRIMARY KEY (developer_tech_stack_id)
);

CREATE TABLE domain (
                        name VARCHAR(30) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        PRIMARY KEY (name)
);

CREATE TABLE job_and_tech_stack (
                                    job_and_tech_stack_id BIGINT NOT NULL,
                                    tech_stack_name VARCHAR(30) NOT NULL,
                                    project_and_job_id BIGINT NOT NULL,
                                    priority INT,
                                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    PRIMARY KEY (job_and_tech_stack_id)
);

CREATE TABLE squad (
                       squad_code VARCHAR(30) NOT NULL,
                       project_code VARCHAR(30) NOT NULL,
                       title VARCHAR(30) NOT NULL,
                       description VARCHAR(255),
                       is_active BOOLEAN NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       estimated_duration DECIMAL(5, 2),
                       estimated_cost DECIMAL(12, 2),
                       origin_type VARCHAR(10) NOT NULL,
                       recommendation_reason TEXT,
                       PRIMARY KEY (squad_code)
);

CREATE TABLE tech_stack (
                            tech_stack_name VARCHAR(30) NOT NULL,
                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            PRIMARY KEY (tech_stack_name)
);

CREATE TABLE user_training_history (
                                       user_trainig_history_id BIGINT NOT NULL,
                                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       updated_by VARCHAR(30) NOT NULL,
                                       training_name VARCHAR(100) NOT NULL,
                                       employee_identification_number VARCHAR(30) NOT NULL,
                                       PRIMARY KEY (user_trainig_history_id)
);

CREATE TABLE training_program (
                                  training_name VARCHAR(100) NOT NULL,
                                  description VARCHAR(255),
                                  training_type VARCHAR(10) NOT NULL,
                                  organizer VARCHAR(30) NOT NULL,
                                  started_at TIMESTAMP NOT NULL,
                                  ended_at TIMESTAMP NOT NULL,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  PRIMARY KEY (training_name)
);

CREATE TABLE squad_employee (
                                squad_employee_id BIGINT NOT NULL,
                                assigned_date DATE NOT NULL,
                                employee_identification_number VARCHAR(30) NOT NULL,
                                project_and_job_id BIGINT NOT NULL,
                                is_leader BOOLEAN NOT NULL DEFAULT FALSE,
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                squad_code VARCHAR(30) NOT NULL,
                                total_skill_score INT,
                                PRIMARY KEY (squad_employee_id)
);

CREATE TABLE member (
                        employee_identification_number VARCHAR(30) NOT NULL,
                        employee_name VARCHAR(30) NOT NULL,
                        password VARCHAR(255) NOT NULL,
                        profile_image_url VARCHAR(100),
                        phone_number VARCHAR(11) NOT NULL,
                        joined_at TIMESTAMP,
                        email VARCHAR(30) NOT NULL,
                        career_years INT DEFAULT 1,
                        salary BIGINT,
                        status VARCHAR(30),
                        grade_code VARCHAR(10),
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        deleted_at TIMESTAMP,
                        role VARCHAR(30) NOT NULL,
                        PRIMARY KEY (employee_identification_number)
);

CREATE TABLE certificate (
                             certificate_name VARCHAR(100) NOT NULL,
                             issuing_organization_id TIMESTAMP NOT NULL,
                             issue_date TIMESTAMP NOT NULL,
                             expiry_date TIMESTAMP NOT NULL,
                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             PRIMARY KEY (certificate_name)
);
